name: settings_feature
description: Feature Configurações do app YummyLog for Clinicians.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  auth_foundation:
    path: ../../foundation/auth
  bloc: ^9.2.0
  cloud_firestore: ^5.6.5
  feature_contract:
    path: ../../shared/feature_contract
  firebase_messaging: ^15.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^8.0.2
  go_router: ^14.6.3
  image_picker: ^1.1.2
  package_app_rating:
    git:
      url: https://github.com/pedroculque/mobile-foundation.git
      ref: main
      path: packages/app_rating_core
  patients_feature:
    path: ../patients
  persistence_foundation:
    path: ../../foundation/persistence
  subscription_foundation:
    path: ../../foundation/subscription
  sync_foundation:
    path: ../../foundation/sync
  ui_kit:
    git:
      url: https://github.com/pedroculque/flutter_ui_kit.git
      ref: main
  url_launcher: ^6.3.1
  yummy_log_l10n:
    path: ../../shared/yummy_log_l10n

dev_dependencies:
  bloc_lint: ^0.3.7
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0
