name: patients_feature
description: Feature de pacientes para o app do clínico.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

dependencies:
  auth_foundation:
    path: ../../foundation/auth
  bloc: ^9.2.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.5
  equatable: ^2.0.7
  feature_contract:
    path: ../../shared/feature_contract
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^8.0.2
  go_router: ^14.6.3
  intl: ^0.20.2
  meal_domain:
    path: ../../shared/meal_domain
  package_app_rating:
    git:
      url: https://github.com/pedroculque/mobile-foundation.git
      ref: main
      path: packages/app_rating_core
  path: ^1.9.0
  path_provider: ^2.1.5
  persistence_foundation:
    path: ../../foundation/persistence
  share_plus: ^10.1.4
  subscription_foundation:
    path: ../../foundation/subscription
  ui_kit:
    git:
      url: https://github.com/pedroculque/flutter_ui_kit.git
      ref: main
  url_launcher: ^6.3.1
  yummy_log_l10n:
    path: ../../shared/yummy_log_l10n

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0
