name: auth_foundation
description: Autenticação (Firebase Auth) para o app Yummy Log.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  cached_network_image: ^3.4.1
  feature_contract:
    path: ../../shared/feature_contract
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^8.0.2
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.3
  ui_kit:
    git:
      url: https://github.com/pedroculque/flutter_ui_kit.git
      ref: main

dev_dependencies:
  bloc_lint: ^0.3.7
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0
